---
# --- ETAPA 1: PREPARAÇÃO COMUM PARA TODAS AS VMS ---
- name: Preparando o ambiente comum do cluster
  hosts: all
  become: true
  tasks:
    - name: Atualizando o cache do apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalando utilitários básicos e dependências Python
      apt:
        name:
          - vim
          - curl
          - python3-pip
          - python3-kubernetes # Já instala a dependência do K8s direto pelo sistema de forma limpa
        state: present

    - name: Baixando o binário do kubectl
      get_url:
        url: "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'


# --- ETAPA 2: CONFIGURAÇÃO DO NÓ MASTER (TELECONSULTA) ---
- name: Instalando o K3s Master na VM Teleconsulta
  hosts: master
  become: true
  tasks:
    - name: Baixando e executando o script do K3s Server forçando o IP público
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
          --bind-address=192.168.56.30 \
          --node-ip=192.168.56.30 \
          --advertise-address=192.168.56.30
      args:
        creates: /usr/local/bin/k3s

    - name: Garantir que o firewall não está bloqueando o Kubernetes (Porta 6443 e 10250)
      shell: |
        iptables -F
        iptables -P INPUT ACCEPT
        iptables -P FORWARD ACCEPT
      ignore_errors: yes

    - name: Capturando o token do cluster gerado pelo Master
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_b64

    - name: Salvando o token em uma variável limpa
      set_fact:
        k3s_token: "{{ k3s_token_b64['content'] | b64decode | trim }}"

    - name: Etiquetando o nó master para Teleconsultoria
      shell: |
        kubectl label node {{ inventory_hostname }} carga=teleconsulta --overwrite
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      ignore_errors: yes
    
    - name: Ajuste para que o kubectl funcione corretamente no usuario vagrant
      shell: |
        mkdir -p /home/vagrant/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
        chown vagrant:vagrant /home/vagrant/.kube/config
      args:
        creates: /home/vagrant/.kube/config


# --- ETAPA 3: CONFIGURAÇÃO DOS NÓS WORKERS (TELEMETRIA E VIDEO) ---
- name: Conectando os nós Workers ao Master
  hosts: workers
  become: true
  tasks:
    - name: Baixando e executando o script do K3s Agent apontando para o Teleconsulta
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.30:6443" K3S_TOKEN="{{ hostvars[groups['master'][0]]['k3s_token'] }}" sh -s - agent \
          --node-ip={{ ansible_host }}
      args:
        creates: /usr/local/bin/k3s-agent


# --- ETAPA 4: ETIQUETANDO OS WORKERS AND DEPLOY ---
- name: Aplicando as regras de negócio nas etiquetas dos Workers
  hosts: all
  become: true
  tasks:
    - name: Aguardar até que todos os nós Workers apareçam na API do K3s
      shell: |
        kubectl get nodes | grep -E "telemetria|video" | wc -l
      register: nodes_count
      until: nodes_count.stdout == "2"
      retries: 12
      delay: 5
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      when: inventory_hostname == 'teleconsulta'

    - name: Etiquetando o nó telemetria
      shell: |
        kubectl label node telemetria carga=telemetria --overwrite
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      ignore_errors: yes
      when: inventory_hostname == 'teleconsulta'

    - name: Etiquetando o nó video
      shell: |
        kubectl label node video carga=video --overwrite
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      ignore_errors: yes
      when: inventory_hostname == 'teleconsulta' #algo
