[master]
teleconsulta ansible_host=192.168.56.30 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/teleconsulta/virtualbox/private_key

[workers]
telemetria ansible_host=192.168.56.40 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/telemetria/virtualbox/private_key
video ansible_host=192.168.56.50 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/video/virtualbox/private_key

[k3s_cluster:children]
master
workers