- name: Aplicando as regras de negócio nas etiquetas dos Workers
  hosts: master
  become: true
  tasks:    
  - name: Garantir que o Namespace 'saude' exista
    kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        definition: "{{ lookup('file', './yaml-kube/namespace.yaml') }}"
        state: present

  - name: Aplicar os deploys de Teleconsulta, Telemetria e Vídeo
    kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        definition: "{{ lookup('file', './yaml-kube/infra-hospitalar.yaml') }}"
        state: present