apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: saude
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-cirurgico
  namespace: saude
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-cirurgico
  template:
    metadata:
      labels:
        app: video-cirurgico
    spec:
      nodeName: video
      containers:
      - name: webrtc-app
        image: registry.k8s.io/e2e-test-images/agnhost:2.45
        args: ["netexec", "--udp-port=10000", "--http-port=8080"]
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 10000
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: video-cirurgico-svc
  namespace: saude
spec:
  type: NodePort
  selector:
    app: video-cirurgico
  ports:
    - name: http-sinalizacao
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: webrtc-midia
      protocol: UDP
      port: 10000
      targetPort: 10000
      nodePort: 31000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleconsulta-clinica
  namespace: saude
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teleconsulta
  template:
    metadata:
      labels:
        app: teleconsulta
    spec:
      nodeName: teleconsulta
      containers:
      - name: app-teleconsulta
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: teleconsulta-svc
  namespace: saude
spec:
  type: NodePort
  selector:
    app: teleconsulta
  ports:
    - name: http-websockets
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30030

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetria-sinais-vitais
  namespace: saude
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-mqtt
  template:
    metadata:
      labels:
        app: broker-mqtt
    spec:
      nodeName: telemetria
      containers:
      - name: mosquitto-broker
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: config-volume
        configMap:
          name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: telemetria-svc
  namespace: saude
spec:
  type: NodePort
  selector:
    app: broker-mqtt
  ports:
    - name: mqtt-port
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31883